### PR TITLE
[qtkeychain] remove from overlay

### PR DESCRIPTION
**Pull request by Be-ing**
https://github.com/microsoft/vcpkg/pull/21420 was merged upstream updating qtkeychain and adding Qt6 compatibility.

### CODE REVIEW

**Comment by Be-ing** [comment]
This is confirmed to work in https://github.com/mixxxdj/mixxx/pull/4432

**Comment by daschuer** [comment]
Please maintain the CI until we have found a decision how to continue with this topic in general. 

I think the required change is just a one line change. No need to argue here and holding this PR back. 

I hope you see, that CI results in a distance are hard to track. I like to have the green checkmarks here.

**Comment by Be-ing** [comment]
The CI on this repository is simply not relevant. This is confirmed to work already.

**Comment by Be-ing** [comment]
https://github.com/mixxxdj/mixxx/blob/main/CODE_OF_CONDUCT.md#no-tolerance-for-harassment
> Sustained disruption or derailing of threads, channels, lists, etc.

**Comment by daschuer** [comment]
Superseded by https://github.com/mixxxdj/vcpkg/pull/36

**Pull request closed without merging**
