### PR TITLE
pthreads link fix 

### PR DESCRIPTION
**Pull request by daschuer**
This includes the https://github.com/microsoft/vcpkg/pull/17011
Which might fix the Debug build of Mixxx

### CODE REVIEW

**Comment by JoergAtGithub** [comment]
I just tried the artifact you provided in zulip - unfortunately the pthread behavior is the same as before.

**Comment by daschuer** [comment]
Thank you for checking. Please post the cmake configure log output. I am especially interested in the lines around:

```
-- Found PThreads4W: optimized;C:/buildenv/mixxx-dependencies-2.3-x64-windows-3d70970e752542db9901e4aa2656f215699dc102/installed/x64-windows/lib/pthreadVC3.lib;debug;C:/buildenv/mixxx-dependencies-2.3-x64-windows-3d70970e752542db9901e4aa2656f215699dc102/installed/x64-windows/debug/lib/pthreadVC3d.lib  
-- PThreads4W_DLL_DIR: C:/buildenv/mixxx-dependencies-2.3-x64-windows-3d70970e752542db9901e4aa2656f215699dc102/installed/x64-windows/include/../bin
```

doe the paths exists?

**Comment by JoergAtGithub** [comment]
**Debug** x64_off:
```
1> [CMake] -- Found lilv: C:/Users/Joerg/source/repos/JoergAtGithub/mixxx/buildenv/mixxx-deps-2.3-x64-windows-8f55ca2/installed/x64-windows/debug/lib/lilv.lib  
1> [CMake] -- Could NOT find Shoutidjc (missing: Shoutidjc_LIBRARY Shoutidjc_INCLUDE_DIR) 
1> [CMake] -- Using internal libshout-idjc
1> [CMake] -- Found PThreads4W: optimized;C:/Users/Joerg/source/repos/JoergAtGithub/mixxx/buildenv/mixxx-deps-2.3-x64-windows-8f55ca2/installed/x64-windows/lib/pthreadVC3.lib;debug;C:/Users/Joerg/source/repos/JoergAtGithub/mixxx/buildenv/mixxx-deps-2.3-x64-windows-8f55ca2/installed/x64-windows/debug/lib/pthreadVC3d.lib  
1> [CMake] -- PThreads4W_DLL_DIR: C:/Users/Joerg/source/repos/JoergAtGithub/mixxx/buildenv/mixxx-deps-2.3-x64-windows-8f55ca2/installed/x64-windows/include/../bin
1> [CMake] -- Found OpenSSL: C:/Users/Joerg/source/repos/JoergAtGithub/mixxx/buildenv/mixxx-deps-2.3-x64-windows-8f55ca2/installed/x64-windows/debug/lib/libcrypto.lib (found version "1.1.1j")  
1> [CMake] -- Looking for __GNU_LIBRARY__
1> [CMake] -- Looking for __GNU_LIBRARY__ - not found
```

The path C:/Users/Joerg/source/repos/JoergAtGithub/mixxx/buildenv/mixxx-deps-2.3-x64-windows-8f55ca2/installed/x64-windows/include/../bin exists, but in it are the release librarys. The Debug librarys are in C:/Users/Joerg/source/repos/JoergAtGithub/mixxx/buildenv/mixxx-deps-2.3-x64-windows-8f55ca2/installed/x64-windows/include/../**debug**/bin

**Comment by daschuer** [comment]
I wonder why there are not two lines one for release and one for debug. 

I have added an additional these lines message for debug in: 
overlay/ports/pthreads/vcpkg-cmake-wrapper.cmake
https://github.com/mixxxdj/vcpkg/blob/4fc035e0d408f62cc5a3437e79feb14d05e3e4c0/overlay/ports/pthreads/vcpkg-cmake-wrapper.cmake#L77

But since it is not there, I assume you have the old file somehow. A caching issue? 
Maybe you need to start over with a clan build

**Comment by daschuer** [comment]
I have just confirmed that the version in /mixxx-deps-2.3-x64-windows-8f55ca2/installed/x64-windows/share/pthreads/vcpkg-cmake-wrapper.cmake is old :-(

**Comment by daschuer** [comment]
Please try to manual replace:
*installed/x64-windows/share/pthread/vcpkg-cmake-wrapper.cmake
*installed/x64-windows/share/pthreads/vcpkg-cmake-wrapper.cmake
*installed/x64-windows/share/pthreads/vcpkg-cmake-wrapper.cmake 
*installed/x64-windows/share/pthreads_windows/
with  
https://raw.githubusercontent.com/mixxxdj/vcpkg/4fc035e0d408f62cc5a3437e79feb14d05e3e4c0/overlay/ports/pthreads/vcpkg-cmake-wrapper.cmake

**Comment by daschuer** [comment]
I think it was a caching issue. I have now bumped the pthreads port version. Lat's have a look.

**Comment by daschuer** [comment]
Rebased, the final version. please verify.

**Comment by JoergAtGithub** [comment]
Verified!!!
Now it works with Debug x64__off and RelWithDebInfo x64__portable !

Thank you!

**Comment by daschuer** [comment]
How is the performance of Mixxx compared to RelWithDebInfo? 
Minimum buffer size with keylock enabled / GUI Lags / DB Lags / Waveforms? 
I am asking because if we can make Debug default for developers?

**Comment by daschuer** [comment]
This is the upstream PR: https://github.com/microsoft/vcpkg/pull/18528

But lets merge this as an overlay and not merge from master to not change anything else just before the release. 

@Holzhaus, Do you agree?

**Comment by Holzhaus** [comment]
OK for me.

**Comment by Holzhaus** [comment]
Thank you.

**Pull request merged**
