### PR TITLE
Master merge

### PR DESCRIPTION
**Pull request by daschuer**
This merges from Microsoft's master branch. I have target this to a new 2.5 branch, to not freeze the 2.4 branch in beta phase. This also adds a Qt6 patch that is required to switch to Qt 6 in a follow up PR. 

It brings the following changes to the packages we use:

 * [angle] Fix crash on macos (#29622) (No issue in Mixxx)
 * [harfbuzz] update to 7.2.0 from 7.0
 * [hidapi] update to 0.14.0 from 0.13.1
 * [libjpeg-turbo] Update usage (#31071)
 * [openssl] correct fipsmodule install (#31142)
 * [openssl] support fips build feature (#30916)
 * [pthreads] Fixed whitespaces in path issue (#31179)
 * [qt5] Update to 5.15.9 from 5.15.8
 * [sqlite3] Fix tool installation with zlib (#31050)
 * [zstd] Fix clang-cl flags (#29992)

### CODE REVIEW

**Comment by JoergAtGithub** [comment]
The artifact with the Windows buildlog is missing, this worked before.
grafik

**Comment by JoergAtGithub** [comment]
Where can I get the BUILDENV_SHA256 for the artifacts? Without I can't test them, since windows_buildenv.bat check for them.

**Comment by daschuer** [comment]
The windows_buildenv.bat does not work for GitHub artifacts for a couple of reasons. 
Is suggest to just replace your vcpkg folder with the one found in the double zipped archive here. 

Does this work for you or is executing the bat file mandatory on windows? If this is the case we should fix it in a way that just calling ninja is enough. 

For a test using GiHub I maintain a patched bat file here: https://github.com/daschuer/mixxx/tree/vcpkg_update_direct_qt6_1015

I will adjust it to have workflow builds from this branch.

**Comment by JoergAtGithub** [comment]
I just downloaded and extracted the zip file manually, adjusted BUILDENV_NAME in windows_buildenv.bat only and executed the bat. Than I could build Mixxx with this buildenv.
BUILDENV_BRANCH and BUILDENV_SHA256 are only needed for the automatic downloading and unzipping.

**Comment by JoergAtGithub** [comment]
The buildenv works for me on Windows11 local builds. Only regression is the missing Windows buildlogs artifact here on GitHub.

**Comment by daschuer** [comment]
Cool, so you can test this as described? 

Is is required to use the bat file on every boot or Is calling ninja from a new CMD.exe sufficient? If not, what is missing? The idea is that everything is chached in the CMakeCache.txt

**Comment by JoergAtGithub** [comment]
I never build from command line. Therefore I only need to execute it once to generate the CMakeSettings.json.

**Comment by daschuer** [comment]
Here are the artifacts for testing: 
https://github.com/daschuer/mixxx/actions/runs/5171761368
A check of an hid mapping would be nice.

**Comment by JoergAtGithub** [comment]
Why is the Logfile of the Build for Windows not available in the artifacts? Is this a regression or just a Github Actions hickup?

**Comment by JoergAtGithub** [comment]
Thank's for explaining the missing build log file. I shortly tested this buildenv on Windows 11, also with HID controller, and it worked for me. Thank you!

**Pull request merged**
