### PR TITLE
build PortAudio with JACK support

### PR DESCRIPTION
**Pull request by Be-ing**

### CODE REVIEW

**Comment by Be-ing** [comment]
I have tested this and it builds on macOS too :smile: https://github.com/Be-ing/vcpkg/runs/3210867320

**Comment by Be-ing** [comment]
Note this will require changing our FindPortAudio.cmake module in Mixxx to export the target as `PortAudio::PortAudio`.

**Review by daschuer — APPROVED** [review]
LGTM, Thank you.

**Comment by daschuer** [comment]
Waiting for CI. 

On the long run, cloning from a private Repro is not the best way forward. 
How is the status to get this merged upstream? 

If this is not possible, we should consider to fork you repro at mixxxdj, or add your changes to the vcpkg port folder.

**Comment by Be-ing** [comment]
https://github.com/PortAudio/portaudio/pull/461 is just waiting for final approval. I hope that will be in the next few days.

**Comment by Be-ing** [comment]
CI passed

**Comment by Be-ing** [comment]
By the way I opened a PR to update JACK upstream: https://github.com/microsoft/vcpkg/pull/19270

**Comment by Be-ing** [comment]
Oops I should have checked the build log...
```
-- Could NOT find JACK (missing: JACK_LIBRARY) 
```

**Comment by Be-ing** [comment]
The failure to find JACK is not a bug in this port. The bug is that the jack2 port did not install the pkgconfig file. I have opened a PR to fix this and update JACK upstream: https://github.com/microsoft/vcpkg/pull/19270

**Pull request merged**
