### PR TITLE
Update to macos-11 and other vcpkg maintanance

### PR DESCRIPTION
**Pull request by daschuer**
This PR moves form the deprecated workflow runner macOS-10.5  to maxOS-11 and from Xcode 12 Xcode_12.4. 
In addition it removes some warnings. 

Mixxx builds using this branch can be found here: 
https://github.com/daschuer/mixxx/actions/runs/3234753984

### CODE REVIEW

**Comment by daschuer** [comment]
@m0dB Can you give the resulting Mixxx macOS build try? I hope changing the CI does not affect the performance. 
https://github.com/daschuer/mixxx/suites/8737107259/artifacts/395471167

The windows build can also be given a smoke test. The changes in the windows environment are only minor though. 
Who has interest to do this? 
https://github.com/daschuer/mixxx/suites/8737107259/artifacts/395471169

Thank you very much.

**Comment by m0dB** [comment]
I'll give it a try tonight!

**Comment by daschuer** [comment]
Thank you.

**Comment by m0dB** [comment]
It behaves as expected (not very smooth but useable). No difference noted from the CI change. Not signed, but I guess that is expected? 

But we definitely need to use QOpenGLWindow on macOS... My branch runs significantly smoother. I need to find time to clean up my code...

**Comment by daschuer** [comment]
Thank you very much for confirm.

**Review by ywwg — APPROVED** [review]

**Pull request merged**
