### PR TITLE
[libshout] remove from overlay

### PR DESCRIPTION
**Pull request by Be-ing**
We are using a vendored copy of the libshout-idjc fork in Mixxx,
so there is no need to build this with vcpkg.

### CODE REVIEW

**Comment by Be-ing** [comment]
ping

**Comment by daschuer** [comment]
CI is failing

**Comment by Be-ing** [comment]
CI is not relevant on this repo.

**Comment by daschuer** [comment]
I do not understand your reasons. 
Please explain how you wish to detect build failures like https://github.com/mixxxdj/vcpkg/pull/32 early.
I also think the binary environment package has still relevance.

**Comment by daschuer** [comment]
Superseded by https://github.com/mixxxdj/vcpkg/pull/37

**Pull request closed without merging**
