### PR TITLE
[soundtouch] Update changed SHA512 of repacked source code archive

### PR DESCRIPTION
**Pull request by daschuer**
For some reasons it has changed.

### CODE REVIEW

**Comment by JoergAtGithub** [comment]
LGTM! Thank you!

**Comment by fwcd** [comment]
Looks like soundtouch hashes are out-of-date again

**Comment by daschuer** [comment]
That's odd. Maybe we should consider to fetch the code from git instead.

**Comment by fwcd** [comment]
I've submitted a PR upstream:

- https://github.com/microsoft/vcpkg/pull/35269

Not sure what's going on here though, these checksums shouldn't change. For reference, this is the current tarball:

[soundtouch-2.3.2.tar.gz](https://github.com/mixxxdj/vcpkg/files/13441344/soundtouch-2.3.2.tar.gz)
```
SHA512: 3d4d6314d6fccb3cb899aee36b90799bb9bf7cf1aad9ff2fff6b18c73e68be7e0e00a3f4e31d5dd340c979236f5474b7ef95d51ddb813f353dde920bdef4cb51
```

If it should change again in the future, we could diff the new one against this one.

**Pull request merged**
