### PR TITLE
Master merge

### PR DESCRIPTION
**Pull request by daschuer**
This merges the current microsoft master branch to 2.5 
this is required because soundtouch has changed the hash codes
Following relevant changes are included: 

   * libsndfile:x64-windows 1.2.0#2 -> 1.2.2
   * openssl:x64-windows  3.1.3 -> 3.1.4
   * qt 6.5.3 -> 6.6.0
   * soundtouch:x64-windows 2.3.1#2 -> 2.3.2
   * sqlite3 3.43.0 -> 3.43.1

In my test building Qt 6.6.0 qtdeclarative fails. Let's see if this happens again.

### CODE REVIEW

**Comment by daschuer** [comment]
This looks almost like a compiler bug: 

```
/Applications/Xcode_12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DGL_SILENCE_DEPRECATION -DQT_ASCII_CAST_WARNINGS -DQT_BUILDING_QT -DQT_BUILD_QMLCOMPILER_LIB -DQT_CORE_LIB -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_UP_TO=0x050000 -DQT_EXPLICIT_QFILE_CONSTRUCTION_FROM_PATH -DQT_LEAN_HEADERS=1 -DQT_MOC_COMPAT -DQT_NETWORK_LIB -DQT_NO_AS_CONST -DQT_NO_AS_CONST=1 -DQT_NO_CAST_TO_ASCII -DQT_NO_EXCEPTIONS -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_NO_QEXCHANGE -DQT_QMLINTEGRATION_LIB -DQT_QML_LIB -DQT_USE_QSTRINGBUILDER -DQT_WARN_DEPRECATED_UP_TO=0x070000 -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -I/Users/runner/mixxx-vcpkg/buildtrees/qtdeclarative/x64-osx-min1015-dbg/src/qmlcompiler/QmlCompiler_autogen/include -I/Users/runner/mixxx-vcpkg/buildtrees/qtdeclarative/x64-osx-min1015-dbg/include -I/Users/runner/mixxx-vcpkg/buildtrees/qtdeclarative/x64-osx-min1015-dbg/include/QtQmlCompiler -I/Users/runner/mixxx-vcpkg/buildtrees/qtdeclarative/src/here-src-6-1fc1828d71.clean/src/qmlcompiler -I/Users/runner/mixxx-vcpkg/buildtrees/qtdeclarative/x64-osx-min1015-dbg/src/qmlcompiler -I/Users/runner/mixxx-vcpkg/buildtrees/qtdeclarative/x64-osx-min1015-dbg/include/QtQmlCompiler/6.6.0 -I/Users/runner/mixxx-vcpkg/buildtrees/qtdeclarative/x64-osx-min1015-dbg/include/QtQmlCompiler/6.6.0/QtQmlCompiler -I/Users/runner/mixxx-vcpkg/buildtrees/qtdeclarative/x64-osx-min1015-dbg/include/QtQml -I/Users/runner/mixxx-vcpkg/buildtrees/qtdeclarative/x64-osx-min1015-dbg/include/QtQmlIntegration -I/Users/runner/mixxx-vcpkg/buildtrees/qtdeclarative/src/here-src-6-1fc1828d71.clean/src/qmlintegration -I/Users/runner/mixxx-vcpkg/buildtrees/qtdeclarative/x64-osx-min1015-dbg/src/qmlintegration -I/Users/runner/mixxx-vcpkg/buildtrees/qtdeclarative/x64-osx-min1015-dbg/src/qml -I/Users/runner/mixxx-vcpkg/buildtrees/qtdeclarative/x64-osx-min1015-dbg/include/QtQml/6.6.0 -I/Users/runner/mixxx-vcpkg/buildtrees/qtdeclarative/x64-osx-min1015-dbg/include/QtQml/6.6.0/QtQml -isystem /Users/runner/mixxx-vcpkg/installed/x64-osx-min1015/include/Qt6/QtCore -isystem /Users/runner/mixxx-vcpkg/installed/x64-osx-min1015/include/Qt6 -isystem /Users/runner/mixxx-vcpkg/installed/x64-osx-min1015/share/Qt6/mkspecs/macx-clang -isystem /Users/runner/mixxx-vcpkg/installed/x64-osx-min1015/include/Qt6/QtNetwork -isystem /Users/runner/mixxx-vcpkg/installed/x64-osx-min1015/include/Qt6/QtCore/6.6.0 -isystem /Users/runner/mixxx-vcpkg/installed/x64-osx-min1015/include/Qt6/QtCore/6.6.0/QtCore -fPIC -g -std=c++17 -arch x86_64 -isysroot /Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -mmacosx-version-min=10.15 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wextra -fno-exceptions -fPIC -ffunction-sections -fdata-sections -fapplication-extension -Winvalid-pch -Xarch_x86_64 -include/Users/runner/mixxx-vcpkg/buildtrees/qtdeclarative/x64-osx-min1015-dbg/src/qmlcompiler/CMakeFiles/QmlCompiler.dir/cmake_pch_x86_64.hxx -MD -MT src/qmlcompiler/CMakeFiles/QmlCompiler.dir/qqmlsa.cpp.o -MF src/qmlcompiler/CMakeFiles/QmlCompiler.dir/qqmlsa.cpp.o.d -o src/qmlcompiler/CMakeFiles/QmlCompiler.dir/qqmlsa.cpp.o -c /Users/runner/mixxx-vcpkg/buildtrees/qtdeclarative/src/here-src-6-1fc1828d71.clean/src/qmlcompiler/qqmlsa.cpp
/Users/runner/mixxx-vcpkg/buildtrees/qtdeclarative/src/here-src-6-1fc1828d71.clean/src/qmlcompiler/qqmlsa.cpp:401:22: warning: loop variable '[key, value]' is always a copy because the range of type 'QtPrivate::QKeyValueRange<const QMultiHash<QString, QQmlJSMetaMethod> &>' does not return a reference [-Wrange-loop-analysis]
    for (const auto &[key, value] : hash.asKeyValueRange()) {
                     ^
/Users/runner/mixxx-vcpkg/buildtrees/qtdeclarative/src/here-src-6-1fc1828d71.clean/src/qmlcompiler/qqmlsa.cpp:401:10: note: use non-reference type 'std::__1::pair<const QString &, const QQmlJSMetaMethod &>'
    for (const auto &[key, value] : hash.asKeyValueRange()) {
         ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/runner/mixxx-vcpkg/buildtrees/qtdeclarative/src/here-src-6-1fc1828d71.clean/src/qmlcompiler/qqmlsa.cpp:537:82: error: expected the class name after '~' to name a destructor
    (*reinterpret_cast<QQmlJSScope::ConstPtr *>(m_data)).QQmlJSScope::ConstPtr::~ConstPtr();
                                                                                 ^
/Users/runner/mixxx-vcpkg/buildtrees/qtdeclarative/src/here-src-6-1fc1828d71.clean/src/qmlcompiler/qqmlsa.cpp:740:22: warning: loop variable '[key, value]' is always a copy because the range of type 'QtPrivate::QKeyValueRange<const QMultiHash<QString, QQmlJSMetaPropertyBinding> &>' does not return a reference [-Wrange-loop-analysis]
    for (const auto &[key, value] : hash.asKeyValueRange()) {
                     ^
/Users/runner/mixxx-vcpkg/buildtrees/qtdeclarative/src/here-src-6-1fc1828d71.clean/src/qmlcompiler/qqmlsa.cpp:740:10: note: use non-reference type 'std::__1::pair<const QString &, const QQmlJSMetaPropertyBinding &>'
    for (const auto &[key, value] : hash.asKeyValueRange()) {
         ^~~~~~~~~~~~~~~~~~~~~~~~~~
2 warnings and 1 error generated.
```

**Comment by JoergAtGithub** [comment]
Can you say something about this "compiler bug", and how you fixed the failing build?

**Comment by daschuer** [comment]
I have just picked a upstream commit before the qt 6.6 update. 
It is probably anyway a good idea to not update to 6.6.0 and stick with the LTS 6.5 for the Mixxx 2.5 release. 

Since Xcode 12.4 is not official supported by QT I have set up an Xcode 13 build here: 
https://github.com/daschuer/vcpkg/actions/runs/6731105295
It fails as well. 

I will file a Qt bug.

**Comment by daschuer** [comment]
This is ready for merge.

**Comment by JoergAtGithub** [comment]
Ok, that explains it to me. Let's merge this now - we can later decide, if we update again or not. Thank you!
Please adust the versions in the PR description to what is finally in this PR.

**Comment by daschuer** [comment]
It was a compiler bug: Xcode 13.2.1 is able to build Qt 6.6.0
https://github.com/daschuer/vcpkg/actions/runs/6742997739

But anyway lets stick with the LTS Qt version

**Pull request merged**
