### PR TITLE
[sndfile] enable external-libs for FLAC and OGG

### PR DESCRIPTION
**Pull request by daschuer**
This aims to fix https://github.com/mixxxdj/mixxx/issues/10880

### CODE REVIEW

**Comment by daschuer** [comment]
@fwcd can you have a look here?

**Comment by fwcd** [comment]
If this builds, I see no reason not to merge this. I could first test this when we have a Mixxx build though.

**Comment by daschuer** [comment]
I think we can just merge it. We have anyway the out of disc issue. 
I considering to prepare a rsync based clean up script.

**Comment by JoergAtGithub** [comment]
I could reproduce https://github.com/mixxxdj/mixxx/issues/10880 on my Windows 11 system. Replacing the buildenv with the version from this PR solved the bug!
Thank you!

**Pull request merged**
