### PR TITLE
[qtkeychain] add Qt6 port and qtkeychain-qt5 to overlay

### PR DESCRIPTION
**Pull request by Be-ing**
temporary measure until https://github.com/microsoft/vcpkg/pull/20185 is merged upstream

### CODE REVIEW

**Comment by daschuer** [comment]
For later reference it s better to plain copy the port first. Than apply the changes in a second commit. Can you rebase it like that?

**Comment by Be-ing** [comment]
That would be tedious in this case. This both does a major update of an existing port and adds a new port.

**Comment by daschuer** [comment]
Shall I jump in and do the work?

**Comment by Be-ing** [comment]
okay if you insist

**Pull request closed without merging**
