### PR TITLE
[qt5-base] Use Qt 5.12.5

### PR DESCRIPTION
**Pull request by fwcd**
Updating to Qt 5.12.5 fixes a crash on macOS that can be reproduced using the current Mixxx 2.4 tree by:

- Opening the settings window
- Closing it using the red button
- Reopening the settings window
- Scrolling
- Mixxx crashes: [mixxx-scroll-crash-1666101497070.txt](https://github.com/mixxxdj/vcpkg/files/9811145/mixxx-scroll-crash-1666101497070.txt)

(Only Mixxx 2.4 seems to be affected, on arm64 and x86_64 macOS, not however Mixxx 2.3). Updating to Qt 5.12.5 seems to fix the issue and doesn't incur the waveform performance regressions that currently prevent us from upgrading to newer Qt versions.

Still, it would probably be good to extensively test Mixxx on Qt 5.12.5 before merging, therefore I'll mark this as draft for now.

### CODE REVIEW

**Comment by fwcd** [comment]
It seems as if 5.12.5 is the last version that doesn't regress waveform performance. Here's two builds for arm64 macOS, the former runs smoothly, the latter does not:

- Qt 5.12.5: https://github.com/fwcd/m1xxx/actions/runs/3269604027
- Qt 5.12.6: https://github.com/fwcd/m1xxx/actions/runs/3273226237

**Comment by daschuer** [comment]
@m0db: can you confirm this?

**Comment by m0dB** [comment]
@daschuer I don't have a arm64 mac, so I can't confirm this.

**Comment by fwcd** [comment]
I've started an x86_64 build using Qt 5.12.5 in CI here: https://github.com/fwcd/m1xxx/actions/runs/3281427824/jobs/5403421350

**Comment by fwcd** [comment]
@m0dB Could you check whether that build runs fine for you? Under Rosetta it seems to run smoothly

**Comment by m0dB** [comment]
Yes, I would say it runs comparable to the official 2.3.3.

**Review by daschuer — APPROVED** [review]
LGTM, Thank you.

**Pull request merged**
