### PR TITLE
[qt5-base] Upgrade to Qt 5.14.2

### PR DESCRIPTION
**Pull request by fwcd**
Migrating the 2.4 environment to Qt 5.14.2 fixes the remaining build issues on Xcode 15/macOS 14 Sonoma from

- #87

TL;DR of the situation is that the fix was introduced somewhere between Qt 5.13.2 and 5.14.0, but seems to be hard to identify[^1]. Simply using the newer Qt lets us also drop another patch, the only downside being that we would have to bump the macOS requirement from 10.12 (Sierra) to 10.13 (High Sierra).

[^1]: My unsuccessful attempt can be found here: https://github.com/fwcd/vcpkg/tree/mixxx/patch-sqlite-build

### CODE REVIEW

**Comment by JoergAtGithub** [comment]
If we need to upgrade Qt anyway, why not use the latest Qt5 version as on Windows?

**Comment by fwcd** [comment]
Good point. My thinking was to keep the changes to the minimum required to get things building again, but if there aren't any blockers, building with the latest Qt 5 would probably let us get rid of quite a few patches.

**Comment by daschuer** [comment]
We have a good amount of experience that every Qt ubgrafe brake something with macOs. I assume it is because the test coverage is probably not too good compared to windows. Given that we are already two month past our original release date, I am hasitating to do any mass Qt changes like proposed here. 

What If we postpone it to 2.4.1? We can immediately release it after 2.4.0 and people have the choice of the full beta tested version or the latest Qt build? 

For the problem here, I see a good chance to find and fix the issue.

**Comment by daschuer** [comment]
I think we can close this is favor of  #87

**Pull request closed without merging**
