### PR TITLE
merge from upstream 

### PR DESCRIPTION
**Pull request by daschuer**
This is required, because the original required msys2-runtime is no longer available for download: 
https://github.com/microsoft/vcpkg/pull/30546 

This also brings updates to these packages we us: 
   * angle[core]: chromium_4472#7 -> chromium_5414#1
   * ffmpeg[avcodec,avdevice,avfilter,avformat,core,swresample,swscale]: 5.0.2#1 -> 5.1.2#5
   * harfbuzz[core]: 5.3.1 -> 7.0.0
   * libflac[core]: 1.3.4#1 -> 1.4.2
   * openssl[core]: 3.0.7#2 -> 3.1.0#1
   * opusfile[core]: 0.12#1 -> 0.12+20221121#1
   * zstd[core]: 1.5.2#3 -> 1.5.4#1

### CODE REVIEW

**Comment by JoergAtGithub** [comment]
I did a short test of 2.4 on Windows11, with the buildenv from the artifacts:

- I didn't notice a difference to the previous buildenv!
- All tests, that passed with the old buildenv, pass with this too!

**Comment by daschuer** [comment]
Cool Thank you for testing. We have unfortunately a build failure with ffmpeg and arm64 macOS. I am just crawling up the history to find the faulty PR. Luckily the first ffmpg 5.1.2 commit is working.

**Comment by daschuer** [comment]
I was able to file an upstream bug: 
https://github.com/microsoft/vcpkg/issues/30659
Unfortunately it is a symptom of a script issue that affects all targets.

**Comment by daschuer** [comment]
Now the issue is fixed. 
The upstream PR is this: https://github.com/microsoft/vcpkg/pull/30692

You can here find Mixxx test builds using this new environment: 
https://github.com/daschuer/mixxx/actions/runs/4628165601

Merge?

**Comment by daschuer** [comment]
Rubberband 3.2 and the ffmpeg patch have been merged. I will re-create this PR based on the new upstream master.

**Comment by JoergAtGithub** [comment]
I downloaded the Windows buildenv from the artifacts and noticed two huge files, which are not in the currnt buildenv of 2.4:
\mixxx\buildenv\mixxx-deps-2.4-x64-windows-035f9c8\installed\x64-windows\lib\ANGLE.lib
\mixxx\buildenv\mixxx-deps-2.4-x64-windows-035f9c8\installed\x64-windows\debug\lib\ANGLE.lib
Each file is ~1GByte of size.
We had ANGLE bundled before, but I couldn't find these files in mixxx-deps-2.4-x64-windows-db02b82

**Comment by JoergAtGithub** [comment]
I found, that it's just renamed, before it was called libANGLE.lib and only 840MByte.

**Comment by JoergAtGithub** [comment]
I build x64_portable and x64_off builds with this buildenv. x64_portable works
With the x64_off build, I ran into a Qt assert (https://github.com/mixxxdj/mixxx/issues/11454), which is most likely a bug in the code of Mixxx itself and not related to this buildenv update.

**Comment by JoergAtGithub** [comment]
The code of this PR looks straight forward. Thanks for upstreaming the FFMPEG overlay!
This buildenv needs further testing in https://github.com/mixxxdj/mixxx/pull/11398, especially on macOS, before we use it as default. But merging this PR doesn't harm anything until we change the default buildenv in Mixxx.
Thank you!

**Comment by daschuer** [comment]
My test build was here: https://github.com/daschuer/mixxx/actions/runs/4642219218. I will prepare an mixxxdj/mixxx PR accordingly

**Pull request merged**
