### PR TITLE
[portaudio] Update overlay to version v19.7.0+2023-04-04

### PR DESCRIPTION
**Pull request by daschuer**
This fixes 
* Crasher with FlexASIO https://github.com/mixxxdj/mixxx/issues/10081
* WASAPI loopback device https://github.com/mixxxdj/mixxx/issues/11427
* Not working Numark Mixtrack Pro FX https://github.com/mixxxdj/mixxx/issues/11393

### CODE REVIEW

**Comment by JoergAtGithub** [comment]
Why adding overlays for pkgconfig and Meson here?

**Comment by daschuer** [comment]
It turns out that our vcpkg 2.3 suffers some rotting. Some required downloads are no longer available. The updated packages are not compatible to the old scripts and the new scripts are not working with the other remaining packages. I have tried to make this branch build, but every fix introduces new problems. Updating to upstream main on the other hand, does IMHO not suite to a stable branch.

So I have decided to only update PortAudio 19.7.0 + our patches and added the minimum required changes for that. This pulls in a minor Jack update 1.9.21 (from 1.9.14)  and a pthreads build scripts update. The pkgconfig and Meson update is required to make the build work that goes not to the result output. 

Than I have added the new files to the existing mixxx-deps zip archive.

**Comment by daschuer** [comment]
The linked windows build used still the old Portaudio version. The last commit should fix it.

**Comment by daschuer** [comment]
Now it is working: 
https://github.com/daschuer/mixxx/suites/12032425437/artifacts/632709730

Even with non ASCII characters: 
grafik

**Comment by daschuer** [comment]
@JoergAtGithub I am glad you found that. There was a merge conflict with changed parameter names and the patches. 

Luckily all our Mixxx patches are now merged and I have prepared a build from the current upstream HEAD. 
This should lower the risk of similar issues with rotted patches. 
Please test this one: 
https://github.com/daschuer/mixxx/suites/12066844096/artifacts/635057674

**Comment by daschuer** [comment]
It works :-) 
grafik

**Comment by JoergAtGithub** [comment]
I tested this on Win7 and Win11. It behaves for me as the old version - note that I'm not affected by these bugs.

**Comment by JoergAtGithub** [comment]
Updating the cache should be Ok for a bugfix release. But it should be noted, that this build.yml no longer generates the complete buildenv from scratch - it all relies on the VCPKG cache.

**Comment by JoergAtGithub** [comment]
Thank you!

**Comment by daschuer** [comment]
> But it should be noted, that this build.yml no longer generates the complete buildenv from scratch

Yes. The issue is that even without this patch the build.yml is not able to generate the complete buildenv.

**Comment by daschuer** [comment]
Thank you for testing.

**Pull request merged**
