### PR TITLE
[libmad] Detect the FPM flag according to the CMAKE_SYSTEM_PROCESSOR

### PR DESCRIPTION
**Pull request by daschuer**
This enables the precision 64 Bit integer math. 
Fixing bug https://github.com/mixxxdj/mixxx/issues/11888

### CODE REVIEW

**Comment by JoergAtGithub** [comment]
How can a patch for `configure.ac` influence the CMake build? Shouldn't this go into `CMakeLists.txt` instead?

**Comment by daschuer** [comment]
libmad is build with autotools (configure) see: 
https://github.com/mixxxdj/vcpkg/blob/23bb59bc6988899a55cbf10a0dbbe8a45dff8dc6/overlay/ports/libmad/portfile.cmake#L22

**Comment by JoergAtGithub** [comment]
The documentation of `vcpkg_cmake_configure` says it "Configure a CMake-based project."
https://learn.microsoft.com/en-us/vcpkg/maintainers/functions/vcpkg_cmake_configure

**Comment by daschuer** [comment]
Oh yes, I was confused. The port uses a custom CMakeList.txt. I have now adjusted that.

**Comment by daschuer** [comment]
still -DFPM_DEFAULT :-(

**Comment by JoergAtGithub** [comment]
Code LGTM! Does it work now?
Please adjust the PR title.

**Comment by daschuer** [comment]
Now the -DFPM_64BIT is used see:
```
[11/13] C:\PROGRA~2\MICROS~2\2019\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\cl.exe   -DASO_ZEROCHECK -DFPM_64BIT -DHAVE_CONFIG_H -D_CRT_SECURE_NO_WARNINGS -D_LIB -D_MBCS  /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\mad.dir\layer3.c.obj /FdCMakeFiles\mad.dir\mad.pdb /FS -c D:\mixxx-vcpkg\buildtrees\libmad\src\2cad30347f-707d5099e3.clean\layer3.c
```

**Comment by JoergAtGithub** [comment]
Thank you!

**Pull request merged**
