### PR TITLE
Osx qt512 fix crosscompile

### PR DESCRIPTION
**Pull request by daschuer**
This PR modifies our vendored Qt 5.12 package in a way that cross compiling is allowed. 
This is includes the change, we have developed for supporting the new Apple M1 devices natively. 
This PR does not bring the native Apple M1 support to Mixxx, it just removes some hassle when building for an M1 device at home. 

This PR has been successful tested here: 
https://github.com/daschuer/mixxx/actions/runs/2638201956

unofficial Apple M1 builds based on this branch can be found here: 
https://github.com/daschuer/mixxx/actions/runs/2638298438

@fwcd
Can you confirm this and do a brief review of the commits? 
Thank you.

### CODE REVIEW

**Comment by fwcd** [comment]
The changes look good from a short glance, though I haven't dug deep enough to be able to comment on anything in detail. The ARM build also seems to run well from some quick smoke testing.

**Comment by PawBud** [comment]
firstly, thanks a lot @daschuer for your work on this till now, I agree with @fwcd that the binary seems to work well, I would like to test it more and will soon update you regarding the same as I discover things that are not working.

**Comment by daschuer** [comment]
@PawBud Diid you collect some experiences? 

In the meantime we have received more tests that this is working:
https://mixxx.zulipchat.com/#narrow/stream/109171-development/topic/macos.20apple.20silicon

@Swiftb0y I think this is safe to merge. What do you think.

**Comment by Swiftb0y** [comment]
I don't understand any of the changes. I can't give any opinion on this PR unfortunately.

**Comment by daschuer** [comment]
I am afraid no one else with commit rights can. 
We just need one to confirm that the contributor tests and reviews are sufficient and the approach is reasonable and finally presses merge.

**Review by Swiftb0y — APPROVED** [review]
The [feedback on zulip](https://mixxx.zulipchat.com/#narrow/stream/109171-development/topic/macos.20apple.20silicon) convinces me that this PR as safe (even though I can't comment on the changes themselves, but it seems like nobody else can).

**Pull request merged**
