### PR TITLE
[portaudio] Add iOS patches

### PR DESCRIPTION
**Pull request by fwcd**
This adds https://github.com/PortAudio/portaudio/pull/881 to PortAudio, enabling builds targeting iOS. Once upstreamed, these patches can be removed.

### CODE REVIEW

**Review by daschuer — APPROVED** [review]
All green. How is the IOS branch compiled? Can we cross-compile it like the M1 build?

**Comment by fwcd** [comment]
Pretty much, most packages should build by just targeting `arm64-ios(-release)`

**Comment by daschuer** [comment]
Do you plan to add a CI runner for this?

**Comment by fwcd** [comment]
Yes. There are some more missing patches for it to run through, but I'll see if I can open a PR soon.

**Comment by fwcd** [comment]
Cross-compiling Qt for arm64 iOS will likely be similar to arm64 macOS in that debug builds will likely not be feasible. How would you suggest doing this under the current branching scheme? Should we add `arm64-ios-release` CI to both 2.5 and 2.5-rel, or just 2.5-rel?

**Comment by daschuer** [comment]
With the package cache, incremental builds are possible. So we may need two attempts to have everything build. 
But do we relay need the debug build? If not let save some energy and only introduce the  arm64-ios-release. 
We can add the debug builds at any time later.

**Comment by fwcd** [comment]
Yeah, my question was more around the branching scheme (IMO release builds are perfectly sufficient), i.e. whether we should add iOS (`arm64-ios-release`) CI to the (non-rel) 2.5 branch too? If so, should we add CI for `arm64-osx-release` to 2.5 too, which currently is only tested in 2.5-rel?

**Comment by daschuer** [comment]
That's a good idea. This is now possible with the new scheme and we can uses it.

**Pull request merged**
