### PR TITLE
Remove obsolete TagLib 1.12 overlay

### PR DESCRIPTION
**Pull request by uklotzde**
...after merging upstream.

### CODE REVIEW

**Comment by Be-ing** [comment]
Have you tested building Mixxx with this?

**Comment by uklotzde** [comment]
Good point, not yet. I don't remember, how do I trigger a new build of Mixxx using the artefacts of this branch?

They merged the 1.12-beta-2 right away and didn't notice :see_no_evil:

**Comment by Be-ing** [comment]
Do you have push access for this repo? You need to make a branch on the upstream repo for the build to get deployed to downloads.mixxx.org to test building Mixxx with it on CI (alternatively, you could download the GitHub Actions artifact and build locally in a VM).

**Comment by uklotzde** [comment]
Building: https://github.com/mixxxdj/vcpkg/actions/runs/651563159

**Comment by uklotzde** [comment]
The new build environment has been uploaded but is not found when building Mixxx:

https://github.com/uklotzde/mixxx/runs/2107874896

**Comment by Be-ing** [comment]
You need to change the URL in tools/windows_buildenv.bat to test a build environment from a different branch.

**Comment by uklotzde** [comment]
> You need to change the URL in tools/windows_buildenv.bat to test a build environment from a different branch.

:see_no_evil: Didn't notice that the build environments are uploaded into separate directories on our server.

**Comment by uklotzde** [comment]
I am also trying to enable FFmpeg. It does not work and I don't see what's missing. FFmpeg is found but the build still ignores  SoundSourceFFmpeg.

**Comment by uklotzde** [comment]
Next try: https://github.com/uklotzde/mixxx/runs/2107976970

**Comment by uklotzde** [comment]
Ping. Builds succeeded.

I didn't pull master again with the updated SQLite 3.35, because the new version is not used by any other platform right now.

**Pull request merged**
