### PR TITLE
Add liblo to the feature list

### PR DESCRIPTION
**Pull request by daschuer**

### CODE REVIEW

**Comment by daschuer** [comment]
I have cleaned the history. I consider this a small addition that it does not rectify to fork a 2.6 branch. Having this merged releases us from some maintenance when developing the OSC interface. What do you think?

**Comment by daschuer** [comment]
@fwcd Can you verify this as well? Here I have picked explicit Xcode_13.1 Without it it would default to Xcode 14.2. What would be best? (This is currently used for the 2.5 and 2.6 branch)

**Comment by fwcd** [comment]
If it builds, I'd say this looks good. Not bumping Xcode too far on 2.5 is probably a good idea, even though in principle it shouldn't matter. Same goes for making sure we use the same Xcode version here and in the mixxx repo.

**Comment by fwcd** [comment]
Ah okay, then I see no reason why this should be an issue

**Comment by daschuer** [comment]
@fwcd can this be merged?

**Comment by fwcd** [comment]
I think so, yes

**Comment by daschuer** [comment]
Ok, than let's merge.

**Pull request merged**
