### PR TITLE
Macos qt drag and drop fix

### PR DESCRIPTION
**Pull request by daschuer**
This aims to fix the drag and drop issue reported here: https://github.com/mixxxdj/mixxx/pull/4717

This PR is on top of https://github.com/mixxxdj/vcpkg/pull/45

### CODE REVIEW

**Comment by fwcd** [comment]
I have filed https://bugs.launchpad.net/mixxx/+bug/1978384 for this, before I saw that you already looked into this. Thanks!

Since we won't get around patching the Qt build in the Intel version either now, we could probably upstream the M1 patches, even if Mixxx doesn't choose to officially provide binaries for ARM macOS, right?

**Comment by daschuer** [comment]
> Since we won't get around patching the Qt build in the Intel version either now, we could probably upstream the M1 patches, even if Mixxx doesn't choose to officially provide binaries for ARM macOS, right?

Yes, but lets go in steps.

**Comment by fwcd** [comment]
I can confirm that the drag-n-drop patch works as expected (with the minor caveat that drag ghost images always seem to appear in the window's top left corner when dragging multiple tracks, this does not impact the actual functionality though and should not block the PR).

**Comment by daschuer** [comment]
Nice news, thank you.

**Comment by daschuer** [comment]
@Swiftb0y: can you have a brief look here? We may merge this at one or the clean up PR first. This one applies upstream patches from QT 5.15

**Comment by daschuer** [comment]
@Swiftb0y This is now rebased to 2.4, ready for review.

**Comment by Swiftb0y** [comment]
Thank you. I don't quite understand what I'm looking at though. The two patch files, where did they originate from?

**Comment by daschuer** [comment]
They are taken form here:
https://github.com/qt/qtbase/commit/52e9c8b4be6718bda1a46859d6b1c13664c57c2a
and 
https://github.com/qt/qtbase/commit/8481a9fc974a1f1dd44a9f82decb18fe2290689f

**Comment by Swiftb0y** [comment]
Ok thanks for clarifying.

**Review by Swiftb0y — APPROVED** [review]

**Pull request merged**
