### PR TITLE
Cherry-pick OpenSSL 3.1.2 onto `2.4`

### PR DESCRIPTION
**Pull request by fwcd**
Motivation: Trying to debug Mixxx with a 2.4 env on arm64 macOS crashes at launch due to a bug in OpenSSL 3.1.0, which presumably has been fixed in 3.1.2:

- https://github.com/openssl/openssl/issues/20753

While the 2.5 branch is already based on a more recent version of the upstream master (see #78), the 2.4 branch still uses the buggy version of OpenSSL, hence this PR which merges the upstream master that includes OpenSSL 3.1.2.

### CODE REVIEW

**Comment by daschuer** [comment]
This PR is huge. Since the beta, I have not merged from master to not have to much untested code in our release.

**Review by daschuer — CHANGES_REQUESTED** [review]
Can you only cherry pick the commits to the `ports/openssl` folder?

**Comment by fwcd** [comment]
That sounds like a reasonable fix, I'll look into that. Should I place it in the `overlay` folder (to avoid messy merge conflicts in the future), with the potential downside of having to manually vendor it for now?

**Comment by daschuer** [comment]
No just use `git cherry-pick` I have done that in this in the past and that will merge cleanly later. We use overlays for changes that are not part of upstream.

**Comment by fwcd** [comment]
Done

**Review by daschuer — APPROVED** [review]
LGTM, Thank you. Waiting for CI

**Pull request merged**
