### PR TITLE
merge from upstream master 

### PR DESCRIPTION
**Pull request by daschuer**
This updates the libraries listed below and removes the no longer necessary -mmacosx-version-min flag form the triplet files. 
 
* ableton 3.0.5 -> 3.0.6
* angle chromium_4472.5 -> chromium_4472.7
* brotli 1.0.9.3 -> 1.0.9.4
* double-conversion 3.2.0 -> 3.2.1
* egl-registry 2021-11-23 -> 2022-09-20
* expat 2.5.0.0 -> 2.5.0.3
* ffmpeg 4.4.1 -> 5.0.2
* freetype 2.12.1.2 -> 2.12.1.3
* harfbuzz 5.0.1 -> 5.3.1 
* hidapi 0.12.0 -> 0.13.1
* libogg 1.3.5.0 -> 1.3.5.1
* libpng 1.6.37 -> 1.6.39
* libpq 14.4.2 -> 14.4.3
* libsndfile 1.1.0 -> 1.2.0
* lz4 1.9.3 -> 1.9.4
* libmp3lame 3.100.9 -> 3.100.10
* opengl-registry 2021-11-17 -> 2022-09-29
* openssl 3.0.7.0 -> 3.0.7.2
* pcre2 10.40.0 -> 10.40.1
* protobuf 3.21.8 -> 3.21.12
* pthreads 3.0.0.12 -> 3.0.013
* qt5 5.15.7 -> 5.15.8 (Windows only)
* taglib 1.12.0 -> 1.13.0
* wavpack 5.5.0 -> 5.6.0
* zstd 1.5.2.1 -> 1.5.2.3

### CODE REVIEW

**Comment by daschuer** [comment]
Mixxx builds using this PR can be found here: 
https://github.com/daschuer/mixxx/actions/runs/3965638620

Who can verify and merge?

**Comment by JoergAtGithub** [comment]
I did some quick tests on Windows11:
-The Mixxx build linked above works fine
-Compiling Mixxx locally with VS2022 using the buildenv ZIP from this PR works
--All tests passed execept:
```
	700 - SoundSourceProxyTest.seekForwardBackward (Failed)
	702 - SoundSourceProxyTest.seekBoundaries (Failed)
	703 - SoundSourceProxyTest.readBeyondEnd (Failed)
	704 - SoundSourceProxyTest.regressionTestCachingReaderChunkJumpForward (Failed)
```
but this is a Windows11 bug https://github.com/mixxxdj/mixxx/issues/11094 and not related to VCPKG

**Comment by JoergAtGithub** [comment]
A test on MacOS is needed too.

**Comment by foss-** [comment]
Crash when double clicking a track in library to add to deck (1 month): https://bin.disroot.org/?6b9206c0564ff848#91gDA7o9ct7e9hH1x2zxsC5hQMfNS6XaUdmVyTVFfWiK

**Comment by daschuer** [comment]
The crash happens in Keyfinder and fftw3: 
```
31  mixxx                         	       0x10250ce52 fftw_plan_dft_c2r_1d + 34
32  mixxx                         	       0x10188121a KeyFinder::InverseFftAdapter::InverseFftAdapter(unsigned int) + 106
```

The fftw3 change is not relevant for MacOS: 
https://github.com/daschuer/vcpkg/commits/master_merge/ports/fftw3

Can you confirm that the crash is not specific to this build?

**Comment by foss-** [comment]
@daschuer not sure how to do that. I was not observing a similar crash in 2.4 main or the other test versions I was using recently. But Mixxx usage has not been high enough to make a statement with certainty.

**Comment by daschuer** [comment]
What is the conclusion here? If we blame this upgrade for the crash we will probably stick very long without any progress. 
As @Swiftb0y pointed out in the original report the source issue can be any dangling pointer anyway. This PR may just shift the memory layout that it happens in fftw3. By luck it is fixed here: https://github.com/mixxxdj/mixxx/pull/11230 

I think we should merge that and fix possible issue during the beta phase. 
@Swiftb0y and @JoergAtGithub. What is your opinion?

**Comment by foss-** [comment]
Tried again to reproduce the crash with https://github.com/daschuer/mixxx/actions/runs/3965638620 but was unable to do so.

I updated library, selected all on analyze and clicked analyze but files were already analyzeed so opted to instead select a few files in library and select reanalyze. Again, no crash.

**Comment by Swiftb0y** [comment]
I think we need to collect more data on the crash. I agree with merging this now and fixing the problem during the beta.

**Pull request merged**
