### PR TITLE
[qt5-base] Upgrade to Qt 5.15.11

### PR DESCRIPTION
**Pull request by fwcd**
As suggested by @JoergAtGithub in https://github.com/mixxxdj/vcpkg/pull/90#issuecomment-1771452402, this branch provides an experimental Qt 5.15.11 environment.

### CODE REVIEW

**Comment by JoergAtGithub** [comment]
The patch qmake_xcode15.patch seems to be the only difference - and is included in the upstream version. Why do we need an overlay here?
Wouldn't be enough to cherry-pick https://github.com/microsoft/vcpkg/pull/34097 and use the normal port instead of the overlay?

**Comment by fwcd** [comment]
We still need all of the cross-compilation machinery since upstream Qt 5 doesn't support that well (or didn't want to include our `qt5-host-tools` hack) if I remember correctly. I've tried merging the upstream `qt5-base` in and it got pretty messy, unfortunately.

**Comment by fwcd** [comment]
https://github.com/microsoft/vcpkg/issues/28835 was the upstream issue, not sure if that still applies though

**Comment by fwcd** [comment]
This probably also needs some more testing... my native Qt 5.15.11 build of Mixxx seems to work mostly fine, except for the EQ knobs, which don't work (neither affecting the audio nor the waveform).

**Comment by fwcd** [comment]
Perhaps, given that the 2.4 release is upcoming, it's not really worth investing a lot of time into this? While I would love to be able to build 2.4 environments on Sonoma to diagnose 2.4 issues, maybe this is too risky to integrate after all? Especially considering that the 5.12 CI build still runs flawlessly and that this only affects developers who wish to build environments locally on the most recent macOS.

Feeling a bit torn here, ideally we would just find the issue that prevents 5.12 from building (see #87), but digging through a [humongous diff](https://github.com/qt/qtbase/compare/v5.13.2...v5.14.0) between Qt versions is no fun either...

**Comment by daschuer** [comment]
Yes, let's postpone this, or even skip it and traight advence to qt6. I see a good chance to just fix the issue itself.

**Comment by fwcd** [comment]
By the way, the EQ issue on my machine was only an artifact of switching between Mixxx versions, the solution being to simply delete the `mixxx.cfg`. See https://mixxx.zulipchat.com/#narrow/stream/267968-testing/topic/2.2E4.20EQ.20not.20working.3F/near/397378876 for details.

But I agree, let's revisit this once we've shipped 2.4.0.

**Comment by daschuer** [comment]
I think we can close this is favour of  #87

**Pull request closed without merging**
