### PR TITLE
Upstream merge

### PR DESCRIPTION
**Pull request by daschuer**
This is an upstream merge that includes the latest PR for wavpack and arm builds https://github.com/microsoft/vcpkg/pull/21790 and the qtkeychain fix https://github.com/microsoft/vcpkg/pull/25018
This comes also with libflac 1.3.4 and libusb 1.0.26

### CODE REVIEW

**Comment by daschuer** [comment]
It was proved building with the mixxx/main here: https://github.com/daschuer/mixxx/actions/runs/2435110621

@Swiftb0y Can you have a look here? This is a prerequisite for installing ms-gsl here: https://github.com/mixxxdj/vcpkg/pull/44

**Comment by Swiftb0y** [comment]
I don't really know what I can review here. I don't really know how vcpkg overlays work. I guess this is just simply merging upstream into our overlay?

**Comment by daschuer** [comment]
Yes, mostly + three extra commit for adjusting to the new upstream. 
So if you do not see anything suspicious, I suggest to merge and build a mixxx/mixxxdj PR for testing. 
A preview is already here: https://github.com/daschuer/mixxx/actions/runs/2435110621

**Review by Swiftb0y — APPROVED** [review]
I read up on vcpkg and the last three commits lgtm. 

Should we wait for Owen to review this too?

**Comment by daschuer** [comment]
> Should we wait for Owen to review this too?

No, I have only requested @ywwg  because he as merged the previous upstream merge. I think you can go ahead and merge.

**Comment by Swiftb0y** [comment]
Can we merge #44 now?

**Comment by daschuer** [comment]
Yes, thank you.

**Pull request merged**
